name: Run E2E Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker-e2e:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Docker
      run: docker compose -f "tests/e2e/docker-compose.yml" up -d

    - name: Start tests
      run: cd tests/e2e && pnpm run test:ci

    - name: Stop containers
      if: always()
      run: docker compose -f "tests/e2e/docker-compose.yml" down
